rsvplist.settings:
  type: config_object
  label: RSVP List Content Type Settings
  mapping:
    allowed_types:
      type: sequence
      label: Content types the RSVP Form can display on
      sequencia:
        type: string
        label: Content type
